version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  windows:
    executor: win/default
    steps:
      - checkout
      - run: 'echo Oh hi!'
  linux:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 'echo Oh hi!'

workflows:
  workflow:
    jobs:
      - windows
      - linux