version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  windows:
    executor: win/default
    steps:
      - checkout
      - run: 'npm i > $null'
      - run: 'node index.js windows'

  macos:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1
    shell: /bin/zsh
    steps:
      - checkout
      - run: 'npm i > /dev/null'
      - run: 'node index.js macos'

  linux:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run: 'npm i > /dev/null'
      - run: 'node index.js linux'

workflows:
  workflow:
    jobs:
      - windows
      - linux
      - macos